name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to latest version

      # Ensure dist folder exists
      - name: Ensure dist folder exists
        run: mkdir -p dist

      # Debug: Test GitHub API access to contributions
      - name: Debug - Test GitHub API access
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/users/Rayan-1737/events || echo "Failed to fetch contribution data"

      # Generate the snake animation with Platane/snk@v3
      - name: Generate GitHub Snake
        uses: Platane/snk@v3  # Updated to v3
        id: snake-gif
        with:
          github_user_name: Rayan-1737
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Debug: Check the generated files
      - name: Debug - List files in dist folder
        run: ls -la dist/

      # Debug: Display the content of the SVG file
      - name: Debug - Show SVG file content
        run: cat dist/github-contribution-grid-snake.svg || echo "SVG file not found"

      # Deploy to GitHub Pages (this will handle pushing to the output branch)
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4  # Updated to latest version
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
