name: Generate Snake

# Runs every 1 hour or manually
on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Ensure dist folder exists
      - name: Ensure dist folder exists
        run: mkdir -p dist

      # Install Node.js (required for snk CLI)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      # Install snk CLI tool
      - name: Install snk CLI
        run: npm install -g @platane/snk

      # Debug: Test GitHub API access to contributions
      - name: Debug - Test GitHub API access
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/users/Rayan-1737/events || echo "Failed to fetch contribution data"

      # Generate snake animation with dark theme manually
      - name: Generate GitHub Snake Manually
        run: |
          snk --user Rayan-1737 --output-svg dist/github-contribution-grid-snake.svg --output-gif dist/github-contribution-grid-snake.gif --palette github-dark --color-snake orange --color-dots '#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Debug: Check the generated files
      - name: Debug - List files in dist folder
        run: ls -la dist/

      # Debug: Display the content of the SVG file
      - name: Debug - Show SVG file content
        run: cat dist/github-contribution-grid-snake.svg || echo "SVG file not found"

      # Show status for debugging
      - name: Show git status
        run: git status

      # Deploy to output branch
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
